#!/usr/bin/python

import sys
import io

import G

from Utils import getkey
from Processor import Processor

if len(sys.argv) < 2:
    error("No filename specified")
    exit(1)

filename = sys.argv[1] 
outfile = sys.argv[2] if len(sys.argv) > 2 else ''.join(['/tmp/',filename,'.html'])

f = io.open(G.log_dir+'/objectdump','w')
html = io.open(outfile, 'w')

p = Processor('', filename, 'html', True, outfile)

p.generate()

#print p.get_text()

html.write(p.get_text())
html.close()

p.postprocess_objects()

f.write(unicode(p.get_objects_as_string()))
f.close()

G.close_log()

print "Wrote results to", outfile
